#!/usr/bin/env bash
# Bash script that will fix the nginx port issue
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
kill "$(pgrep 'nginx' | head -1)"
