#!/usr/bin/env bash
# displays Best School 10 times,
# the 9th iteration, displays Hi before it

num=1

while [ $num -le 10 ]
do
	echo "Best School"
	if [ $num -eq 9 ]
	then
		echo "Hi"
	fi
	(( num++ ))
done
