#!/usr/bin/env bash
# displays numbers from 1 to 20 and bad luck from
# China or Japan or Italy after 4 or 9 or 17

num=1

while [ $num -le 20 ]
do
	echo "$num"
	case $num in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	(( num++ ))
done
