#!/usr/bin/env bash
# Bash script that run nginx webserver as nginx and configures
# nginx to listen to port 8080

pkill apache
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
