#!/usr/bin/env bash
# nginx as nginx and fix port from 80 to 8080
pkill apache
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
